# Generated by Django 3.0.8 on 2020-10-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0004_prestamo_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='agregado',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
