# Generated by Django 3.0.8 on 2020-10-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0005_prestamo_agregado'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='modificado_por',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
