# Generated by Django 3.0.8 on 2020-10-09 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0004_perfil_modificado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Descripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio_vendido', models.PositiveIntegerField(blank=True, default=None)),
                ('precio_pagado', models.PositiveIntegerField(blank=True, default=None)),
                ('precio_compra', models.PositiveIntegerField(blank=True, default=None)),
                ('cantidad', models.FloatField(default=None)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('area', models.CharField(default='Sellado', max_length=100)),
                ('modificado_por', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DescripcionInterna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio_vendido', models.PositiveIntegerField(blank=True, default=None)),
                ('precio_pagado', models.PositiveIntegerField(blank=True, default=None)),
                ('precio_compra', models.PositiveIntegerField(blank=True, default=None)),
                ('cantidad', models.FloatField(default=None)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('area', models.CharField(default='Peletizado', max_length=100)),
                ('modificado_por', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sueldo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(blank=True, max_length=100)),
                ('sueldo', models.PositiveIntegerField()),
                ('valor', models.FloatField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('agregado', models.CharField(default=None, max_length=100)),
                ('modificado_por', models.CharField(default=None, max_length=100)),
                ('perfil', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Perfil')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
