# Generated by Django 3.0.8 on 2020-09-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sueldos', '0002_sueldo_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='sueldo',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
