# Generated by Django 3.0.8 on 2020-09-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sueldos', '0004_auto_20200902_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcion',
            name='cantidad',
            field=models.FloatField(default=None),
        ),
    ]
