# Generated by Django 3.0.8 on 2020-10-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sueldos', '0005_auto_20200919_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='sueldo',
            name='agregado',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
