# Generated by Django 3.0.8 on 2020-10-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sueldos', '0006_sueldo_agregado'),
    ]

    operations = [
        migrations.AddField(
            model_name='descripcion',
            name='area',
            field=models.CharField(default='Sellado', max_length=100),
        ),
    ]
