# Generated by Django 3.0.8 on 2020-10-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sueldos', '0008_auto_20201008_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sueldo',
            name='sueldo',
            field=models.FloatField(),
        ),
    ]
