# Generated by Django 3.0.8 on 2020-10-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sueldos', '0009_auto_20201008_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sueldo',
            name='sueldo',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sueldo',
            name='valor',
            field=models.FloatField(),
        ),
    ]
