# Generated by Django 3.0.8 on 2020-10-09 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0004_perfil_modificado_por'),
        ('sueldos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduccionInterna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(default=None, max_length=20)),
                ('cantidad', models.FloatField()),
                ('precio_pagado', models.PositiveIntegerField()),
                ('nota', models.CharField(blank=True, max_length=100)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('agregado', models.CharField(default=None, max_length=100)),
                ('modificado_por', models.CharField(default=None, max_length=100)),
                ('descripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sueldos.DescripcionInterna')),
                ('perfil', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Perfil')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(default=None, max_length=20)),
                ('cantidad', models.FloatField()),
                ('precio_pagado', models.PositiveIntegerField()),
                ('nota', models.CharField(blank=True, max_length=100)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('agregado', models.CharField(default=None, max_length=100)),
                ('modificado_por', models.CharField(default=None, max_length=100)),
                ('descripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sueldos.Descripcion')),
                ('perfil', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Perfil')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fijo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(default=None, max_length=20)),
                ('precio_pagado', models.PositiveIntegerField()),
                ('nota', models.CharField(blank=True, max_length=100)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('agregado', models.CharField(default=None, max_length=100)),
                ('modificado_por', models.CharField(default=None, max_length=100)),
                ('perfil', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Perfil')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
