# Generated by Django 3.0.8 on 2020-07-21 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_perfil_area'),
        ('salarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fijo',
            name='perfil',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Perfil'),
        ),
        migrations.AddField(
            model_name='produccion',
            name='area',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='produccion',
            name='perfil',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Perfil'),
        ),
    ]
