# Generated by Django 3.0.8 on 2020-07-29 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salarios', '0004_fijo_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='cantidad',
            field=models.FloatField(),
        ),
    ]
