# Generated by Django 3.0.8 on 2020-09-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salarios', '0005_auto_20200728_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='fijo',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='produccion',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
