# Generated by Django 3.0.8 on 2020-10-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salarios', '0006_auto_20200902_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='fijo',
            name='agregado',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='produccion',
            name='agregado',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
