# Generated by Django 3.0.8 on 2020-10-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salarios', '0007_auto_20201003_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='fijo',
            name='modificado_por',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='produccion',
            name='modificado_por',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
