# Generated by Django 3.0.8 on 2020-10-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_perfil_identificador'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='modificado_por',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
