# Generated by Django 3.0.8 on 2020-09-03 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sueldos', '0003_sueldo_modificado'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='descripcion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sueldos.Descripcion'),
        ),
    ]
