# Generated by Django 3.0.8 on 2020-09-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='saldo',
            field=models.FloatField(default=None),
        ),
    ]
