# Generated by Django 3.0.8 on 2020-10-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_compra_modificado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='modificado_por',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
