# Generated by Django 3.0.8 on 2020-09-19 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_remove_perfil_area'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sueldos', '0005_auto_20200919_1719'),
        ('clientes', '0004_cliente_saldo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('celular', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=100)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('nota', models.CharField(blank=True, max_length=100)),
                ('saldo', models.FloatField(default=None)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Adquisicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('precio_compra', models.PositiveIntegerField()),
                ('nota', models.CharField(blank=True, max_length=100)),
                ('compra', models.PositiveIntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('descripcion', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sueldos.Descripcion')),
                ('nombre', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
                ('perfil', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Perfil')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
