# Generated by Django 3.0.8 on 2020-09-20 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adquisicion',
            name='nombre',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='proveedores.Proveedor'),
        ),
    ]
