# Generated by Django 3.0.8 on 2020-10-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_auto_20200919_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='adquisicion',
            name='credito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='identificador',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
